CREATE DATABASE IF NOT EXISTS `bookstore` /*!40100 DEFAULT CHARACTER SET UTF8 */;
USE `bookstore`;

CREATE TABLE books (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  genre INTEGER,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;